export const FETCH_VACANCIES = 'vacancies/START_VACANCIES'
export const FILTER_VACANCIES = 'vacancies/FILTER_VACANCIES'
export const ADD_SEARCHING_CATEGORY = 'vacancies/ADD_SEARCHING_CATEGORY'
export const REMOVE_SEARCHING_CATEGORY = 'vacancies/REMOVE_SEARCHING_CATEGORY'